=== vLeapGroup/warps-specs/schemas/v0.2.0.schema.json
{
  "$ref": "#/definitions/Warp",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "BaseWarpActionInputType": {
      "enum": [
        "string",
        "uint8",
        "uint16",
        "uint32",
        "uint64",
        "biguint",
        "boolean",
        "address",
        "codemeta",
        "hex",
        "esdt",
        "nft",
        "opt",
        "list"
      ],
      "type": "string"
    },
    "Warp": {
      "additionalProperties": false,
      "properties": {
        "actions": {
          "items": {
            "$ref": "#/definitions/WarpAction"
          },
          "type": "array"
        },
        "description": {
          "type": ["string", "null"]
        },
        "meta": {
          "$ref": "#/definitions/WarpMeta"
        },
        "name": {
          "type": "string"
        },
        "next": {
          "type": "string"
        },
        "preview": {
          "type": "string"
        },
        "protocol": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "vars": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      },
      "required": [
        "protocol",
        "name",
        "title",
        "description",
        "preview",
        "actions"
      ],
      "type": "object"
    },
    "WarpAction": {
      "anyOf": [
        {
          "$ref": "#/definitions/WarpContractAction"
        },
        {
          "$ref": "#/definitions/WarpQueryAction"
        },
        {
          "$ref": "#/definitions/WarpLinkAction"
        }
      ]
    },
    "WarpActionInput": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": ["string", "null"]
        },
        "max": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "$ref": "#/definitions/WarpVarPlaceholder"
            }
          ]
        },
        "min": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "$ref": "#/definitions/WarpVarPlaceholder"
            }
          ]
        },
        "modifier": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "options": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "pattern": {
          "type": "string"
        },
        "patternDescription": {
          "type": "string"
        },
        "position": {
          "$ref": "#/definitions/WarpActionInputPosition"
        },
        "required": {
          "type": "boolean"
        },
        "source": {
          "$ref": "#/definitions/WarpActionInputSource"
        },
        "type": {
          "$ref": "#/definitions/WarpActionInputType"
        }
      },
      "required": ["name", "type", "position", "source"],
      "type": "object"
    },
    "WarpActionInputPosition": {
      "enum": [
        "value",
        "transfer",
        "arg:1",
        "arg:2",
        "arg:3",
        "arg:4",
        "arg:5",
        "arg:6",
        "arg:7",
        "arg:8",
        "arg:9",
        "arg:10"
      ],
      "type": "string"
    },
    "WarpActionInputSource": {
      "enum": ["field", "query"],
      "type": "string"
    },
    "WarpActionInputType": {
      "anyOf": [
        {
          "$ref": "#/definitions/BaseWarpActionInputType"
        },
        {
          "const": "opt:string",
          "type": "string"
        },
        {
          "const": "opt:uint8",
          "type": "string"
        },
        {
          "const": "opt:uint16",
          "type": "string"
        },
        {
          "const": "opt:uint32",
          "type": "string"
        },
        {
          "const": "opt:uint64",
          "type": "string"
        },
        {
          "const": "opt:biguint",
          "type": "string"
        },
        {
          "const": "opt:boolean",
          "type": "string"
        },
        {
          "const": "opt:address",
          "type": "string"
        },
        {
          "const": "opt:codemeta",
          "type": "string"
        },
        {
          "const": "opt:hex",
          "type": "string"
        },
        {
          "const": "opt:esdt",
          "type": "string"
        },
        {
          "const": "opt:nft",
          "type": "string"
        },
        {
          "const": "opt:opt",
          "type": "string"
        },
        {
          "const": "opt:list",
          "type": "string"
        },
        {
          "const": "list:string",
          "type": "string"
        },
        {
          "const": "list:uint8",
          "type": "string"
        },
        {
          "const": "list:uint16",
          "type": "string"
        },
        {
          "const": "list:uint32",
          "type": "string"
        },
        {
          "const": "list:uint64",
          "type": "string"
        },
        {
          "const": "list:biguint",
          "type": "string"
        },
        {
          "const": "list:boolean",
          "type": "string"
        },
        {
          "const": "list:address",
          "type": "string"
        },
        {
          "const": "list:codemeta",
          "type": "string"
        },
        {
          "const": "list:hex",
          "type": "string"
        },
        {
          "const": "list:esdt",
          "type": "string"
        },
        {
          "const": "list:nft",
          "type": "string"
        },
        {
          "const": "list:opt",
          "type": "string"
        },
        {
          "const": "list:list",
          "type": "string"
        },
        {
          "const": "list:opt:string",
          "type": "string"
        },
        {
          "const": "list:opt:uint8",
          "type": "string"
        },
        {
          "const": "list:opt:uint16",
          "type": "string"
        },
        {
          "const": "list:opt:uint32",
          "type": "string"
        },
        {
          "const": "list:opt:uint64",
          "type": "string"
        },
        {
          "const": "list:opt:biguint",
          "type": "string"
        },
        {
          "const": "list:opt:boolean",
          "type": "string"
        },
        {
          "const": "list:opt:address",
          "type": "string"
        },
        {
          "const": "list:opt:codemeta",
          "type": "string"
        },
        {
          "const": "list:opt:hex",
          "type": "string"
        },
        {
          "const": "list:opt:esdt",
          "type": "string"
        },
        {
          "const": "list:opt:nft",
          "type": "string"
        },
        {
          "const": "list:opt:opt",
          "type": "string"
        },
        {
          "const": "list:opt:list",
          "type": "string"
        },
        {
          "const": "opt:list:string",
          "type": "string"
        },
        {
          "const": "opt:list:uint8",
          "type": "string"
        },
        {
          "const": "opt:list:uint16",
          "type": "string"
        },
        {
          "const": "opt:list:uint32",
          "type": "string"
        },
        {
          "const": "opt:list:uint64",
          "type": "string"
        },
        {
          "const": "opt:list:biguint",
          "type": "string"
        },
        {
          "const": "opt:list:boolean",
          "type": "string"
        },
        {
          "const": "opt:list:address",
          "type": "string"
        },
        {
          "const": "opt:list:codemeta",
          "type": "string"
        },
        {
          "const": "opt:list:hex",
          "type": "string"
        },
        {
          "const": "opt:list:esdt",
          "type": "string"
        },
        {
          "const": "opt:list:nft",
          "type": "string"
        },
        {
          "const": "opt:list:opt",
          "type": "string"
        },
        {
          "const": "opt:list:list",
          "type": "string"
        }
      ]
    },
    "WarpActionType": {
      "enum": ["contract", "query", "link"],
      "type": "string"
    },
    "WarpContractAction": {
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "string"
        },
        "args": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "description": {
          "type": ["string", "null"]
        },
        "func": {
          "type": ["string", "null"]
        },
        "gasLimit": {
          "type": "number"
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "next": {
          "type": "string"
        },
        "transfers": {
          "items": {
            "$ref": "#/definitions/WarpContractActionTransfer"
          },
          "type": "array"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        },
        "value": {
          "type": "string"
        }
      },
      "required": ["type", "label", "address", "func", "args", "gasLimit"],
      "type": "object"
    },
    "WarpContractActionTransfer": {
      "additionalProperties": false,
      "properties": {
        "amount": {
          "type": "string"
        },
        "nonce": {
          "type": "number"
        },
        "token": {
          "type": "string"
        }
      },
      "required": ["token"],
      "type": "object"
    },
    "WarpLinkAction": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": ["string", "null"]
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        },
        "url": {
          "type": "string"
        }
      },
      "required": ["type", "label", "url"],
      "type": "object"
    },
    "WarpMeta": {
      "additionalProperties": false,
      "properties": {
        "createdAt": {
          "type": "string"
        },
        "creator": {
          "type": "string"
        },
        "hash": {
          "type": "string"
        }
      },
      "required": ["hash", "creator", "createdAt"],
      "type": "object"
    },
    "WarpQueryAction": {
      "additionalProperties": false,
      "properties": {
        "abi": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "args": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "description": {
          "type": ["string", "null"]
        },
        "func": {
          "type": ["string", "null"]
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        }
      },
      "required": ["type", "label", "address", "func", "args"],
      "type": "object"
    },
    "WarpVarPlaceholder": {
      "type": "string"
    }
  }
}

=== vLeapGroup/warps-specs/examples/vleap/raffle-participate.json
{
  "protocol": "warp:0.2.0",
  "name": "Raffle: Participate",
  "title": "Participate in a Raffle",
  "description": "<p>Participate in the raffle sent to you. ID: {{RAFFLE_ID}}</p>",
  "preview": "https://vleap.io/images/external/warps/raffle-participate.jpg",
  "vars": {
    "RAFFLE_ID": "query:raffle",
    "EXTRA_INFO_LABEL": "query:extra-info",
    "ENTRY_FEE": "query:entry-fee"
  },
  "actions": [
    {
      "type": "contract",
      "label": "Participate now",
      "address": "erd1qqqqqqqqqqqqqpgqht0nht73ewg4mxr8nd89v5p8cfryjjlfl3tskqtqpw",
      "func": "participate",
      "args": ["uint64:{{RAFFLE_ID}}"],
      "value": "{{ENTRY_FEE}}",
      "gasLimit": 10000000,
      "inputs": [
        {
          "name": "{{EXTRA_INFO_LABEL}}",
          "type": "string",
          "position": "arg:2",
          "source": "field",
          "required": true
        }
      ]
    }
  ]
}

=== vLeapGroup/warps-specs/examples/v0.1.0-peerme-burn-for-tag.json
{
  "protocol": "warp:0.1.0",
  "name": "Burn for Tag",
  "title": "Burn $SUPER for PeerTags",
  "description": "Each burn of {{REQUIRED_AMOUNT}} $SUPER will qualify your for a set of PeerTags (4 tags) delivered to your door.",
  "preview": "https://peerme.io/images/external/warps/burn-for-tag-preview.jpg",
  "vars": {
    "REQUIRED_AMOUNT": "query:amount"
  },
  "actions": [
    {
      "type": "contract",
      "label": "Burn for Tag now",
      "address": "erd1qqqqqqqqqqqqqpgq4kns8he9r84c58ed3jjuam3tp7u9zl4n27rsy2kv6u",
      "func": "burnForTrust",
      "args": [],
      "gasLimit": 20000000,
      "inputs": [
        {
          "name": "SUPER to burn",
          "type": "esdt",
          "position": "transfer",
          "source": "field",
          "required": true,
          "options": ["SUPER-507aa6"],
          "min": "{{REQUIRED_AMOUNT}}"
        }
      ]
    },
    {
      "type": "link",
      "label": "View Tags",
      "description": "View details of PeerTags.",
      "url": "https://peerme.io/peer-tags"
    }
  ],
  "next": "https://tally.so/r/w4PvNk"
}

=== vLeapGroup/warps-specs/examples/v0.1.0-esdt-pause.json
{
  "protocol": "warp:0.1.0",
  "name": "Pause Token",
  "title": "Pause all operations of a token.",
  "description": "The manager of an ESDT token may choose to suspend all transactions of the token, except minting, freezing/unfreezing and wiping.",
  "preview": "https://vleap.io/images/external/warps/multiversx-docs.jpg",
  "actions": [
    {
      "type": "contract",
      "label": "Pause now",
      "address": "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u",
      "func": "pause",
      "args": [],
      "gasLimit": 60000000,
      "inputs": [
        {
          "name": "Token Identifier",
          "type": "string",
          "position": "arg:1",
          "source": "field",
          "required": true
        }
      ]
    },
    {
      "type": "link",
      "label": "Read docs",
      "description": "Find more information about the ESDT standard.",
      "url": "https://docs.multiversx.com/tokens/fungible-tokens"
    }
  ]
}

=== vLeapGroup/warps-specs/examples/v0.1.0-esdt-issue.json
{
  "protocol": "warp:0.1.0",
  "name": "ESDT Creator",
  "title": "Create a fungible token (ESDT).",
  "description": "The fungible token will be created on the MultiversX blockchain.",
  "preview": "https://docs.multiversx.com/img/social.jpg",
  "actions": [
    {
      "type": "contract",
      "label": "Create now",
      "address": "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u",
      "func": "issue",
      "args": [],
      "value": "50000000000000000",
      "gasLimit": 60000000,
      "inputs": [
        {
          "name": "Token Name",
          "type": "string",
          "position": "arg:1",
          "source": "field",
          "required": true
        },
        {
          "name": "Token Ticker",
          "type": "string",
          "position": "arg:2",
          "source": "field",
          "required": true
        },
        {
          "name": "Initial Supply",
          "type": "bigint",
          "position": "arg:3",
          "source": "field",
          "required": true
        },
        {
          "name": "Token Decimals",
          "type": "uint8",
          "position": "arg:4",
          "source": "field",
          "required": true
        }
      ]
    },
    {
      "type": "link",
      "label": "Read docs",
      "description": "Find more information about ESDT.",
      "url": "https://docs.multiversx.com/tokens/fungible-tokens"
    }
  ]
}

=== vLeapGroup/warps-specs/examples/v0.1.0-esdt-unfreeze.json
{
  "protocol": "warp:0.1.0",
  "name": "Unfreeze Token",
  "title": "Unfreeze the tokens owned by an account.",
  "description": "The manager of an ESDT token may unfreeze the tokens held by a specific Account. As a consequence, the tokens may be transferred to or from the frozen Account.",
  "preview": "https://vleap.io/images/external/warps/multiversx-docs.jpg",
  "actions": [
    {
      "type": "contract",
      "label": "Unfreeze now",
      "address": "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u",
      "func": "unFreeze",
      "args": [],
      "gasLimit": 60000000,
      "inputs": [
        {
          "name": "Token Identifier",
          "type": "string",
          "position": "arg:1",
          "source": "field",
          "required": true
        },
        {
          "name": "Account Address",
          "type": "address",
          "position": "arg:2",
          "source": "field",
          "required": true
        }
      ]
    },
    {
      "type": "link",
      "label": "Read docs",
      "description": "Find more information about the ESDT standard.",
      "url": "https://docs.multiversx.com/tokens/fungible-tokens"
    }
  ]
}

=== vLeapGroup/warps-specs/examples/peerme/entity-propose.json
{
  "protocol": "warp:0.4.0",
  "name": "Entity: Propose",
  "title": "Propose an Entity",
  "description": "Propose an entity to the community.",
  "preview": "https://peerme.io/images/external/warps/entity-propose-preview.jpg",
  "vars": {
    "REQUIRED_AMOUNT": "query:amount"
  },
  "actions": [
    {
      "type": "contract",
      "label": "Burn for Tag now",
      "address": "erd1qqqqqqqqqqqqqpgq4kns8he9r84c58ed3jjuam3tp7u9zl4n27rsy2kv6u",
      "func": "burnForTrust",
      "args": [],
      "gasLimit": 20000000,
      "inputs": [
        {
          "name": "SUPER to burn",
          "type": "esdt",
          "position": "transfer",
          "source": "field",
          "required": true,
          "options": ["SUPER-507aa6"],
          "min": "{{REQUIRED_AMOUNT}}"
        }
      ]
    },
    {
      "type": "link",
      "label": "View Tags",
      "description": "View details of PeerTags.",
      "url": "https://peerme.io/peer-tags"
    }
  ],
  "next": "https://tally.so/r/w4PvNk"
}

=== vLeapGroup/warps-specs/examples/v0.1.0-esdt-unpause.json
{
  "protocol": "warp:0.1.0",
  "name": "Unpause Token",
  "title": "Unpause all operations of a token.",
  "description": "The manager of an ESDT token may choose to resume all transactions of the token after it has been paused.",
  "preview": "https://vleap.io/images/external/warps/multiversx-docs.jpg",
  "actions": [
    {
      "type": "contract",
      "label": "Unpause now",
      "address": "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u",
      "func": "unPause",
      "args": [],
      "gasLimit": 60000000,
      "inputs": [
        {
          "name": "Token Identifier",
          "type": "string",
          "position": "arg:1",
          "source": "field",
          "required": true
        }
      ]
    },
    {
      "type": "link",
      "label": "Read docs",
      "description": "Find more information about the ESDT standard.",
      "url": "https://docs.multiversx.com/tokens/fungible-tokens"
    }
  ]
}
