=== vLeapGroup/warps-specs/schemas/v0.2.0.schema.json
{
  "$ref": "#/definitions/Warp",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "BaseWarpActionInputType": {
      "enum": [
        "string",
        "uint8",
        "uint16",
        "uint32",
        "uint64",
        "biguint",
        "boolean",
        "address",
        "codemeta",
        "hex",
        "esdt",
        "nft",
        "opt",
        "list"
      ],
      "type": "string"
    },
    "Warp": {
      "additionalProperties": false,
      "properties": {
        "actions": {
          "items": {
            "$ref": "#/definitions/WarpAction"
          },
          "type": "array"
        },
        "description": {
          "type": ["string", "null"]
        },
        "meta": {
          "$ref": "#/definitions/WarpMeta"
        },
        "name": {
          "type": "string"
        },
        "next": {
          "type": "string"
        },
        "preview": {
          "type": "string"
        },
        "protocol": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "vars": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      },
      "required": [
        "protocol",
        "name",
        "title",
        "description",
        "preview",
        "actions"
      ],
      "type": "object"
    },
    "WarpAction": {
      "anyOf": [
        {
          "$ref": "#/definitions/WarpContractAction"
        },
        {
          "$ref": "#/definitions/WarpQueryAction"
        },
        {
          "$ref": "#/definitions/WarpLinkAction"
        }
      ]
    },
    "WarpActionInput": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": ["string", "null"]
        },
        "max": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "$ref": "#/definitions/WarpVarPlaceholder"
            }
          ]
        },
        "min": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "$ref": "#/definitions/WarpVarPlaceholder"
            }
          ]
        },
        "modifier": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "options": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "pattern": {
          "type": "string"
        },
        "patternDescription": {
          "type": "string"
        },
        "position": {
          "$ref": "#/definitions/WarpActionInputPosition"
        },
        "required": {
          "type": "boolean"
        },
        "source": {
          "$ref": "#/definitions/WarpActionInputSource"
        },
        "type": {
          "$ref": "#/definitions/WarpActionInputType"
        }
      },
      "required": ["name", "type", "position", "source"],
      "type": "object"
    },
    "WarpActionInputPosition": {
      "enum": [
        "value",
        "transfer",
        "arg:1",
        "arg:2",
        "arg:3",
        "arg:4",
        "arg:5",
        "arg:6",
        "arg:7",
        "arg:8",
        "arg:9",
        "arg:10"
      ],
      "type": "string"
    },
    "WarpActionInputSource": {
      "enum": ["field", "query"],
      "type": "string"
    },
    "WarpActionInputType": {
      "anyOf": [
        {
          "$ref": "#/definitions/BaseWarpActionInputType"
        },
        {
          "const": "opt:string",
          "type": "string"
        },
        {
          "const": "opt:uint8",
          "type": "string"
        },
        {
          "const": "opt:uint16",
          "type": "string"
        },
        {
          "const": "opt:uint32",
          "type": "string"
        },
        {
          "const": "opt:uint64",
          "type": "string"
        },
        {
          "const": "opt:biguint",
          "type": "string"
        },
        {
          "const": "opt:boolean",
          "type": "string"
        },
        {
          "const": "opt:address",
          "type": "string"
        },
        {
          "const": "opt:codemeta",
          "type": "string"
        },
        {
          "const": "opt:hex",
          "type": "string"
        },
        {
          "const": "opt:esdt",
          "type": "string"
        },
        {
          "const": "opt:nft",
          "type": "string"
        },
        {
          "const": "opt:opt",
          "type": "string"
        },
        {
          "const": "opt:list",
          "type": "string"
        },
        {
          "const": "list:string",
          "type": "string"
        },
        {
          "const": "list:uint8",
          "type": "string"
        },
        {
          "const": "list:uint16",
          "type": "string"
        },
        {
          "const": "list:uint32",
          "type": "string"
        },
        {
          "const": "list:uint64",
          "type": "string"
        },
        {
          "const": "list:biguint",
          "type": "string"
        },
        {
          "const": "list:boolean",
          "type": "string"
        },
        {
          "const": "list:address",
          "type": "string"
        },
        {
          "const": "list:codemeta",
          "type": "string"
        },
        {
          "const": "list:hex",
          "type": "string"
        },
        {
          "const": "list:esdt",
          "type": "string"
        },
        {
          "const": "list:nft",
          "type": "string"
        },
        {
          "const": "list:opt",
          "type": "string"
        },
        {
          "const": "list:list",
          "type": "string"
        },
        {
          "const": "list:opt:string",
          "type": "string"
        },
        {
          "const": "list:opt:uint8",
          "type": "string"
        },
        {
          "const": "list:opt:uint16",
          "type": "string"
        },
        {
          "const": "list:opt:uint32",
          "type": "string"
        },
        {
          "const": "list:opt:uint64",
          "type": "string"
        },
        {
          "const": "list:opt:biguint",
          "type": "string"
        },
        {
          "const": "list:opt:boolean",
          "type": "string"
        },
        {
          "const": "list:opt:address",
          "type": "string"
        },
        {
          "const": "list:opt:codemeta",
          "type": "string"
        },
        {
          "const": "list:opt:hex",
          "type": "string"
        },
        {
          "const": "list:opt:esdt",
          "type": "string"
        },
        {
          "const": "list:opt:nft",
          "type": "string"
        },
        {
          "const": "list:opt:opt",
          "type": "string"
        },
        {
          "const": "list:opt:list",
          "type": "string"
        },
        {
          "const": "opt:list:string",
          "type": "string"
        },
        {
          "const": "opt:list:uint8",
          "type": "string"
        },
        {
          "const": "opt:list:uint16",
          "type": "string"
        },
        {
          "const": "opt:list:uint32",
          "type": "string"
        },
        {
          "const": "opt:list:uint64",
          "type": "string"
        },
        {
          "const": "opt:list:biguint",
          "type": "string"
        },
        {
          "const": "opt:list:boolean",
          "type": "string"
        },
        {
          "const": "opt:list:address",
          "type": "string"
        },
        {
          "const": "opt:list:codemeta",
          "type": "string"
        },
        {
          "const": "opt:list:hex",
          "type": "string"
        },
        {
          "const": "opt:list:esdt",
          "type": "string"
        },
        {
          "const": "opt:list:nft",
          "type": "string"
        },
        {
          "const": "opt:list:opt",
          "type": "string"
        },
        {
          "const": "opt:list:list",
          "type": "string"
        }
      ]
    },
    "WarpActionType": {
      "enum": ["contract", "query", "link"],
      "type": "string"
    },
    "WarpContractAction": {
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "string"
        },
        "args": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "description": {
          "type": ["string", "null"]
        },
        "func": {
          "type": ["string", "null"]
        },
        "gasLimit": {
          "type": "number"
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "next": {
          "type": "string"
        },
        "transfers": {
          "items": {
            "$ref": "#/definitions/WarpContractActionTransfer"
          },
          "type": "array"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        },
        "value": {
          "type": "string"
        }
      },
      "required": ["type", "label", "address", "func", "args", "gasLimit"],
      "type": "object"
    },
    "WarpContractActionTransfer": {
      "additionalProperties": false,
      "properties": {
        "amount": {
          "type": "string"
        },
        "nonce": {
          "type": "number"
        },
        "token": {
          "type": "string"
        }
      },
      "required": ["token"],
      "type": "object"
    },
    "WarpLinkAction": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": ["string", "null"]
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        },
        "url": {
          "type": "string"
        }
      },
      "required": ["type", "label", "url"],
      "type": "object"
    },
    "WarpMeta": {
      "additionalProperties": false,
      "properties": {
        "createdAt": {
          "type": "string"
        },
        "creator": {
          "type": "string"
        },
        "hash": {
          "type": "string"
        }
      },
      "required": ["hash", "creator", "createdAt"],
      "type": "object"
    },
    "WarpQueryAction": {
      "additionalProperties": false,
      "properties": {
        "abi": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "args": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "description": {
          "type": ["string", "null"]
        },
        "func": {
          "type": ["string", "null"]
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        }
      },
      "required": ["type", "label", "address", "func", "args"],
      "type": "object"
    },
    "WarpVarPlaceholder": {
      "type": "string"
    }
  }
}

=== vLeapGroup/warps-specs/examples/v0.1.0-esdt-issue-prefilled.json
{
  "protocol": "warp:0.1.0",
  "name": "Create Token",
  "title": "Create a fungible token (ESDT).",
  "description": "The fungible token will be created on the MultiversX blockchain.",
  "preview": "https://vleap.io/images/external/warps/multiversx-docs.jpg",
  "actions": [
    {
      "type": "contract",
      "label": "Create now",
      "address": "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u",
      "func": "issue",
      "args": [],
      "value": "50000000000000000",
      "gasLimit": 60000000,
      "inputs": [
        {
          "name": "name",
          "type": "string",
          "position": "arg:1",
          "source": "query",
          "required": true,
          "min": 3,
          "max": 50,
          "pattern": "^[a-zA-Z0-9]+$",
          "patternDescription": "Only letters and numbers are allowed."
        },
        {
          "name": "ticker",
          "type": "string",
          "position": "arg:2",
          "source": "query",
          "required": true,
          "min": 3,
          "max": 10,
          "pattern": "^[A-Z0-9]+$",
          "patternDescription": "Only uppercase letters and numbers are allowed."
        },
        {
          "name": "supply",
          "type": "biguint",
          "position": "arg:3",
          "source": "query",
          "required": true,
          "modifier": "scale:decimals"
        },
        {
          "name": "decimals",
          "type": "uint8",
          "position": "arg:4",
          "source": "query",
          "required": true,
          "min": 0,
          "max": 18
        }
      ]
    },
    {
      "type": "link",
      "label": "Read docs",
      "description": "Find more information about ESDT.",
      "url": "https://docs.multiversx.com/tokens/fungible-tokens"
    }
  ]
}

=== vLeapGroup/warps-specs/examples/vleap/raffle-get-participants.json
{
  "protocol": "warp:0.2.0",
  "name": "Raffle: Get Participants",
  "title": "Get Participants",
  "description": "<p>Get the participants of the raffle sent to you. ID: {{RAFFLE_ID}}</p>",
  "preview": "https://vleap.io/images/external/warps/raffle-participate.jpg",
  "vars": {
    "RAFFLE_ID": "query:raffle"
  },
  "actions": [
    {
      "type": "query",
      "label": "Get Participants",
      "address": "erd1qqqqqqqqqqqqqpgqht0nht73ewg4mxr8nd89v5p8cfryjjlfl3tskqtqpw",
      "func": "getParticipations",
      "args": ["uint64:{{RAFFLE_ID}}"],
      "abi": "hash:779a71a57507759eb4aca42a34e513f140d77e8711fb681ede142c1cb037c257"
    }
  ]
}

=== vLeapGroup/warps-specs/examples/v0.1.0-vleap-guild-stake.json
{
  "protocol": "warp:0.1.0",
  "name": "vLeap xMoney Guild Stake",
  "title": "Stake with the vLeap xMoney Guild",
  "description": "<p>Easily stake with <a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://guilds.xmoney.com/guilds/erd1qqqqqqqqqqqqqpgq2kwtwtlcv297v45kqakyl0x8ddytvv9dhu4qzprdfk\">our Guild</a> on xMoney.</p>",
  "preview": "https://guilds.xmoney.com/assets/img/guild-hero-screenshots@2x.png",
  "actions": [
    {
      "type": "contract",
      "label": "Stake UTK now",
      "address": "erd1qqqqqqqqqqqqqpgq2kwtwtlcv297v45kqakyl0x8ddytvv9dhu4qzprdfk",
      "func": "stakeFarm",
      "args": [],
      "gasLimit": 25000000,
      "inputs": [
        {
          "name": "UTK Stake",
          "type": "esdt",
          "position": "transfer",
          "source": "field",
          "required": true
        }
      ]
    },
    {
      "type": "link",
      "label": "View Guild",
      "description": "View the details of the vLeap xMoney Guild.",
      "url": "https://guilds.xmoney.com/guilds/erd1qqqqqqqqqqqqqpgq2kwtwtlcv297v45kqakyl0x8ddytvv9dhu4qzprdfk"
    }
  ]
}

=== vLeapGroup/warps-specs/examples/v0.1.0-xexchange-swap.json
{
  "protocol": "warp:0.1.0",
  "name": "xExchange: Swap eGold to SUPER",
  "title": "Swap eGold to SUPER",
  "description": "Swap eGold to SUPER on xExchange.",
  "preview": "https://vleap.io/images/external/warps/xexchange-swap.png",
  "actions": [
    {
      "type": "contract",
      "label": "Swap now",
      "address": "erd1qqqqqqqqqqqqqpgq957r57dca0h6avq2mtfd7tvxlhcp3r4y0n4sdq7clt",
      "func": "swapTokensFixedInput",
      "args": ["string:SUPER-19c5c5", "biguint:1"],
      "gasLimit": 10000000,
      "inputs": [
        {
          "name": "WEGLD Amount",
          "type": "esdt",
          "position": "transfer",
          "source": "field",
          "required": true,
          "min": 1,
          "options": ["WEGLD-a28c59"]
        }
      ]
    }
  ]
}

=== vLeapGroup/warps-specs/examples/vleap/tip.json
{
  "protocol": "warp:1.0.0",
  "name": "Tipping: Tip",
  "title": "Tip a User",
  "description": "Tip a user with any token.",
  "preview": "https://vleap.ai/images/external/warps/tip.jpg",
  "vars": {
    "RECEIVER": "query:to"
  },
  "actions": [
    {
      "type": "contract",
      "label": "Tip now",
      "address": "erd1qqqqqqqqqqqqqpgqszhrp70u9vmutn9yr4xgjhrfwakxzvd5l3ts3aem69",
      "func": "tip",
      "args": ["address:{{RECEIVER}}"],
      "gasLimit": 5000000,
      "inputs": [
        {
          "name": "Amount",
          "type": "esdt",
          "position": "transfer",
          "source": "field",
          "required": true
        },
        {
          "name": "Note",
          "type": "string",
          "position": "arg:2",
          "source": "field",
          "required": true
        }
      ]
    }
  ]
}

=== vLeapGroup/warps-specs/examples/vleap/raffle-participate3.json
{
  "protocol": "warp:0.2.0",
  "name": "Raffle: Participate",
  "title": "Participate in a Raffle",
  "description": "<p>Participate in the raffle sent to you. ID: {{RAFFLE_ID}}</p>",
  "preview": "https://vleap.io/images/external/warps/raffle-participate.jpg",
  "vars": {
    "RAFFLE_ID": "query:raffle",
    "INFO1": "query:info1-label",
    "INFO2": "query:info2-label",
    "INFO3": "query:info3-label",
    "ENTRY_FEE": "query:entry-fee"
  },
  "actions": [
    {
      "type": "contract",
      "label": "Participate now",
      "address": "erd1qqqqqqqqqqqqqpgqht0nht73ewg4mxr8nd89v5p8cfryjjlfl3tskqtqpw",
      "func": "participate",
      "args": ["uint64:{{RAFFLE_ID}}"],
      "value": "{{ENTRY_FEE}}",
      "gasLimit": 10000000,
      "inputs": [
        {
          "name": "{{INFO1}}",
          "type": "string",
          "position": "arg:2",
          "source": "field",
          "required": true
        },
        {
          "name": "{{INFO2}}",
          "type": "string",
          "position": "arg:3",
          "source": "field",
          "required": true
        },
        {
          "name": "{{INFO3}}",
          "type": "string",
          "position": "arg:4",
          "source": "field",
          "required": true
        }
      ]
    }
  ]
}

=== vLeapGroup/warps-specs/examples/v0.1.0-esdt-freeze.json
{
  "protocol": "warp:0.1.0",
  "name": "Freeze Token",
  "title": "Freeze the tokens owned by an account.",
  "description": "The manager of an ESDT token may freeze the tokens held by a specific Account. As a consequence, no tokens may be transferred to or from the frozen Account.",
  "preview": "https://vleap.io/images/external/warps/multiversx-docs.jpg",
  "actions": [
    {
      "type": "contract",
      "label": "Freeze now",
      "address": "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u",
      "func": "freeze",
      "args": [],
      "gasLimit": 60000000,
      "inputs": [
        {
          "name": "Token Identifier",
          "type": "string",
          "position": "arg:1",
          "source": "field",
          "required": true
        },
        {
          "name": "Account Address",
          "type": "address",
          "position": "arg:2",
          "source": "field",
          "required": true
        }
      ]
    },
    {
      "type": "link",
      "label": "Read docs",
      "description": "Find more information about the ESDT standard.",
      "url": "https://docs.multiversx.com/tokens/fungible-tokens"
    }
  ]
}

=== vLeapGroup/warps-specs/examples/v0.1.0-delegate-egld.json
{
  "protocol": "warp:0.1.0",
  "name": "Stake Egld",
  "title": "Ready to stake EGLD with us?",
  "description": "Stake with us to enable extra benefits across all our platforms.",
  "preview": "https://cdn.prod.website-files.com/6597cc7be68d63ec0c8ce33f/660441460ae47e18853dd348_staking-v4.webp",
  "actions": [
    {
      "type": "contract",
      "label": "Stake now",
      "address": "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllllscktaww",
      "func": "delegate",
      "args": [],
      "gasLimit": 10000000,
      "inputs": [
        {
          "name": "value",
          "description": "Amount of eGold to delegate.",
          "type": "biguint",
          "position": "value",
          "source": "field",
          "required": true,
          "min": 1,
          "modifier": "scale:18"
        }
      ]
    },
    {
      "type": "link",
      "label": "Learn more",
      "description": "Find more information about staking eGold.",
      "url": "https://multiversx.com/egld"
    }
  ]
}
