=== vLeapGroup/warps-specs/schemas/v1.0.0.schema.json
{
  "$ref": "#/definitions/Warp",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Warp": {
      "additionalProperties": false,
      "properties": {
        "actions": {
          "items": {
            "$ref": "#/definitions/WarpAction"
          },
          "type": "array"
        },
        "bot": {
          "type": "string"
        },
        "description": {
          "type": ["string", "null"]
        },
        "meta": {
          "$ref": "#/definitions/WarpMeta"
        },
        "name": {
          "type": "string"
        },
        "next": {
          "type": "string"
        },
        "preview": {
          "type": "string"
        },
        "protocol": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "vars": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      },
      "required": ["protocol", "name", "title", "description", "actions"],
      "type": "object"
    },
    "WarpAction": {
      "anyOf": [
        {
          "$ref": "#/definitions/WarpTransferAction"
        },
        {
          "$ref": "#/definitions/WarpContractAction"
        },
        {
          "$ref": "#/definitions/WarpQueryAction"
        },
        {
          "$ref": "#/definitions/WarpCollectAction"
        },
        {
          "$ref": "#/definitions/WarpLinkAction"
        }
      ]
    },
    "WarpActionInput": {
      "additionalProperties": false,
      "properties": {
        "as": {
          "type": "string"
        },
        "bot": {
          "type": "string"
        },
        "description": {
          "type": ["string", "null"]
        },
        "max": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "$ref": "#/definitions/WarpVarPlaceholder"
            }
          ]
        },
        "min": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "$ref": "#/definitions/WarpVarPlaceholder"
            }
          ]
        },
        "modifier": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "options": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "pattern": {
          "type": "string"
        },
        "patternDescription": {
          "type": "string"
        },
        "position": {
          "$ref": "#/definitions/WarpActionInputPosition"
        },
        "required": {
          "type": "boolean"
        },
        "source": {
          "$ref": "#/definitions/WarpActionInputSource"
        },
        "type": {
          "$ref": "#/definitions/WarpActionInputType"
        }
      },
      "required": ["name", "type", "position", "source"],
      "type": "object"
    },
    "WarpActionInputPosition": {
      "enum": [
        "receiver",
        "value",
        "transfer",
        "arg:1",
        "arg:2",
        "arg:3",
        "arg:4",
        "arg:5",
        "arg:6",
        "arg:7",
        "arg:8",
        "arg:9",
        "arg:10",
        "data"
      ],
      "type": "string"
    },
    "WarpActionInputSource": {
      "enum": ["field", "query"],
      "type": "string"
    },
    "WarpActionInputType": {
      "type": "string"
    },
    "WarpActionType": {
      "enum": ["transfer", "contract", "query", "collect", "link"],
      "type": "string"
    },
    "WarpCollectAction": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": ["string", "null"]
        },
        "destination": {
          "additionalProperties": false,
          "properties": {
            "headers": {
              "additionalProperties": {
                "type": "string"
              },
              "type": "object"
            },
            "method": {
              "enum": ["GET", "POST"],
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          },
          "required": ["url", "method", "headers"],
          "type": "object"
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "next": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        }
      },
      "required": ["type", "label", "destination"],
      "type": "object"
    },
    "WarpContractAction": {
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "string"
        },
        "args": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "description": {
          "type": ["string", "null"]
        },
        "func": {
          "type": ["string", "null"]
        },
        "gasLimit": {
          "type": "number"
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "next": {
          "type": "string"
        },
        "transfers": {
          "items": {
            "$ref": "#/definitions/WarpContractActionTransfer"
          },
          "type": "array"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        },
        "value": {
          "type": "string"
        }
      },
      "required": ["type", "label", "address", "func", "args", "gasLimit"],
      "type": "object"
    },
    "WarpContractActionTransfer": {
      "additionalProperties": false,
      "properties": {
        "amount": {
          "type": "string"
        },
        "nonce": {
          "type": "number"
        },
        "token": {
          "type": "string"
        }
      },
      "required": ["token"],
      "type": "object"
    },
    "WarpLinkAction": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": ["string", "null"]
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        },
        "url": {
          "type": "string"
        }
      },
      "required": ["type", "label", "url"],
      "type": "object"
    },
    "WarpMeta": {
      "additionalProperties": false,
      "properties": {
        "createdAt": {
          "type": "string"
        },
        "creator": {
          "type": "string"
        },
        "hash": {
          "type": "string"
        }
      },
      "required": ["hash", "creator", "createdAt"],
      "type": "object"
    },
    "WarpQueryAction": {
      "additionalProperties": false,
      "properties": {
        "abi": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "args": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "description": {
          "type": ["string", "null"]
        },
        "func": {
          "type": "string"
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        }
      },
      "required": ["type", "label", "address", "func", "args"],
      "type": "object"
    },
    "WarpTransferAction": {
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "string"
        },
        "data": {
          "type": "string"
        },
        "description": {
          "type": ["string", "null"]
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "next": {
          "type": "string"
        },
        "transfers": {
          "items": {
            "$ref": "#/definitions/WarpContractActionTransfer"
          },
          "type": "array"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        },
        "value": {
          "type": "string"
        }
      },
      "required": ["type", "label"],
      "type": "object"
    },
    "WarpVarPlaceholder": {
      "type": "string"
    }
  }
}

=== vLeapGroup/warps-specs/examples/bober/piggy-bank.json
{
  "protocol": "warp:1.0.0",
  "name": "Bober Piggy Wallet: Deposit eGold",
  "title": "Deposit eGold into the Bober Piggy Wallet",
  "description": "The Piggy Wallet fuels the future of BOBER. Contribute to fund exciting initiatives like CEX/DEX listings, impactful marketing campaigns, and further development on MultiversX, driving growth and expanding our reach.",
  "preview": "https://tools.multiversx.com/assets-cdn/accounts/erd1qqqqqqqqqqqqqpgq332rrs5lk3pz606uvsnwrgl9kcfa8leyveqsh3arun/icon.svg",
  "actions": [
    {
      "type": "transfer",
      "label": "Deposit now",
      "address": "erd1qqqqqqqqqqqqqpgq332rrs5lk3pz606uvsnwrgl9kcfa8leyveqsh3arun",
      "inputs": [
        {
          "name": "Amount",
          "type": "biguint",
          "position": "value",
          "source": "field",
          "required": true,
          "min": 0.01,
          "modifier": "scale:18"
        }
      ]
    }
  ]
}

=== vLeapGroup/warps-specs/examples/momentum.json
{
  "protocol": "warp:1.0.0",
  "name": "Momentum: Proof of Pod",
  "title": "Claim your Proof of Pod",
  "preview": "https://vleap.ai/images/external/warps/momentum-podcast.png",
  "description": "Sign the transaction to claim your Proof of Pod.",
  "actions": [
    {
      "type": "transfer",
      "label": "Claim PoP",
      "address": "erd1q4j9h0r3qfhd79jc0r6ctue5edlptt50prrgug057yksgafum46spha4hp",
      "data": "string:MOMENTUM"
    }
  ]
}

=== vLeapGroup/warps-specs/examples/joai/onboarding.json
{
  "protocol": "warp:1.0.0",
  "name": "JoAi: Onboarding",
  "title": "Onboarding",
  "description": "Onboarding for JoAi.",
  "bot": "Welcome the user to JoAi. Then proceed to collect the required information.",
  "vars": {
    "COLLECT_API_URL": "env:COLLECT_API_URL",
    "COLLECT_API_KEY": "env:COLLECT_API_KEY"
  },
  "actions": [
    {
      "type": "collect",
      "label": "Submit now",
      "destination": {
        "url": "{{COLLECT_API_URL}}",
        "method": "POST",
        "headers": {
          "Authorization": "Bearer {{COLLECT_API_KEY}}"
        }
      },
      "inputs": [
        {
          "name": "User Name",
          "as": "userName",
          "bot": "The users name for further identification.",
          "type": "string",
          "position": "arg:1",
          "source": "field",
          "required": true
        },
        {
          "name": "Source",
          "description": "How did you discover JoAi? Was it a Google search, friend recommendation, or blog post?",
          "as": "source",
          "bot": "How the user discovered JoAi. Give examples like Google search, friend recommendation, blog post, etc.",
          "type": "string",
          "position": "arg:2",
          "source": "field",
          "required": true
        }
      ]
    }
  ]
}

=== vLeapGroup/warps-specs/examples/xalliance/onboarding.json
{
  "protocol": "warp:1.2.0",
  "name": "xAlliance: Grant Request",
  "title": "Request a Grant",
  "description": "Some description about the grant request.",
  "bot": "Guide the user through the grant request process.",
  "vars": {
    "COLLECT_API_URL": "env:COLLECT_API_URL",
    "COLLECT_API_KEY": "env:COLLECT_API_KEY"
  },
  "actions": [
    {
      "type": "collect",
      "label": "Submit now",
      "destination": {
        "url": "{{COLLECT_API_URL}}",
        "method": "POST",
        "headers": {
          "Authorization": "Bearer {{COLLECT_API_KEY}}"
        }
      },
      "inputs": [
        {
          "name": "Name",
          "as": "name",
          "bot": "The name of the user.",
          "type": "string",
          "position": "arg:1",
          "source": "field",
          "required": true
        },
        {
          "name": "Email",
          "as": "email",
          "bot": "The email address of the user.",
          "type": "string",
          "position": "arg:2",
          "source": "field",
          "required": true
        },
        {
          "name": "Telegram Username",
          "as": "telegramUsername",
          "bot": "The Telegram username of the user.",
          "type": "string",
          "position": "arg:3",
          "source": "field",
          "required": true
        },
        {
          "name": "X (Twitter) Username",
          "as": "xUsername",
          "bot": "The X (Twitter) username of the user.",
          "type": "string",
          "position": "arg:4",
          "source": "field",
          "required": true
        },
        {
          "name": "Discord Username",
          "as": "discordUsername",
          "bot": "The Discord username of the user.",
          "type": "string",
          "position": "arg:5",
          "source": "field",
          "required": true
        },
        {
          "name": "Proof of Work",
          "description": "Please provide any projects, work, and references that can help us get to know you and your work a little bit better. Include links to your best moments.",
          "as": "proofOfWork",
          "bot": "To determine the users previous work and experience.",
          "type": "string",
          "position": "arg:6",
          "source": "field",
          "required": true
        },
        {
          "name": "Project Title",
          "description": "Please provide the title of the project you are applying for.",
          "as": "projectTitle",
          "bot": "About the project the user is applying for.",
          "type": "string",
          "position": "arg:7",
          "source": "field",
          "required": true
        },
        {
          "name": "Idea Oneline",
          "description": "Please provide a one-liner about the project you are applying for.",
          "as": "ideaOneline",
          "bot": "About the project the user is applying for.",
          "type": "string",
          "position": "arg:8",
          "source": "field",
          "required": true
        }
      ]
    }
  ]
}

=== vLeapGroup/warps-specs/examples/multiversx/staking-undelegate.json
{
  "protocol": "warp:0.1.0",
  "name": "Undelegate Egld",
  "title": "Undelegate your EGLD",
  "description": "Undelegate your EGLD to enable extra benefits across all our platforms.",
  "actions": [
    {
      "type": "contract",
      "label": "Undelegate now",
      "address": "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllllscktaww",
      "func": "unDelegate",
      "args": [],
      "gasLimit": 10000000,
      "inputs": [
        {
          "name": "value",
          "description": "Amount of eGold to undelegate.",
          "type": "biguint",
          "position": "arg:1",
          "source": "field",
          "required": true,
          "min": 1,
          "modifier": "scale:18"
        }
      ]
    }
  ]
}

=== vLeapGroup/warps-specs/examples/multiversx/staking-rewards-redelegate.json
{
  "protocol": "warp:2.0.0",
  "name": "MultiversX Staking: Restake",
  "title": "Restake",
  "description": "Restake staking rewards for the current user.",
  "vars": {
    "CONTRACT_ADDRESS": "query:contract"
  },
  "actions": [
    {
      "type": "contract",
      "label": "Restake now",
      "address": "{{CONTRACT_ADDRESS}}",
      "func": "reDelegateRewards",
      "args": [],
      "gasLimit": 10000000
    }
  ]
}

=== vLeapGroup/warps-specs/examples/ici/buy-sft.json
{
  "protocol": "warp:0.5.0",
  "name": "Example heading",
  "title": "Example title",
  "description": "Example description",
  "actions": [
    {
      "type": "contract",
      "label": "Buy now",
      "address": "erd1qqqqqqqqqqqqqpgqra34kjj9zu6jvdldag72dyknnrh2ts9aj0wqp4acqh",
      "func": "buySft",
      "args": ["uint64:518", "string:APDN-65a887", "uint64:114", "biguint:1"],
      "value": "1000000000000000",
      "gasLimit": 10000000
    },
    {
      "type": "link",
      "label": "Learn more",
      "description": "Find more information about SFT.",
      "url": "https://nft.ici.ro"
    }
  ]
}

=== vLeapGroup/warps-specs/examples/joai/name-update.json
{
  "protocol": "warp:1.0.0",
  "name": "JoAi: Name Update",
  "title": "Update your name",
  "description": "Update your name to JoAi.",
  "vars": {
    "COLLECT_API_KEY": "env:COLLECT_API_KEY"
  },
  "actions": [
    {
      "type": "collect",
      "label": "Submit now",
      "destination": {
        "url": "https://devnet-api.joai.ai/warps/collect",
        "method": "POST",
        "headers": {
          "Authorization": "Bearer {{COLLECT_API_KEY}}"
        }
      },
      "inputs": [
        {
          "name": "User Name",
          "as": "userName",
          "bot": "The users name for further identification.",
          "type": "string",
          "position": "arg:1",
          "source": "field",
          "required": true,
          "min": 3
        }
      ]
    }
  ]
}
