=== vLeapGroup/warps-specs/schemas/v1.0.0.schema.json
{
  "$ref": "#/definitions/Warp",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Warp": {
      "additionalProperties": false,
      "properties": {
        "actions": {
          "items": {
            "$ref": "#/definitions/WarpAction"
          },
          "type": "array"
        },
        "bot": {
          "type": "string"
        },
        "description": {
          "type": ["string", "null"]
        },
        "meta": {
          "$ref": "#/definitions/WarpMeta"
        },
        "name": {
          "type": "string"
        },
        "next": {
          "type": "string"
        },
        "preview": {
          "type": "string"
        },
        "protocol": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "vars": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      },
      "required": ["protocol", "name", "title", "description", "actions"],
      "type": "object"
    },
    "WarpAction": {
      "anyOf": [
        {
          "$ref": "#/definitions/WarpTransferAction"
        },
        {
          "$ref": "#/definitions/WarpContractAction"
        },
        {
          "$ref": "#/definitions/WarpQueryAction"
        },
        {
          "$ref": "#/definitions/WarpCollectAction"
        },
        {
          "$ref": "#/definitions/WarpLinkAction"
        }
      ]
    },
    "WarpActionInput": {
      "additionalProperties": false,
      "properties": {
        "as": {
          "type": "string"
        },
        "bot": {
          "type": "string"
        },
        "description": {
          "type": ["string", "null"]
        },
        "max": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "$ref": "#/definitions/WarpVarPlaceholder"
            }
          ]
        },
        "min": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "$ref": "#/definitions/WarpVarPlaceholder"
            }
          ]
        },
        "modifier": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "options": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "pattern": {
          "type": "string"
        },
        "patternDescription": {
          "type": "string"
        },
        "position": {
          "$ref": "#/definitions/WarpActionInputPosition"
        },
        "required": {
          "type": "boolean"
        },
        "source": {
          "$ref": "#/definitions/WarpActionInputSource"
        },
        "type": {
          "$ref": "#/definitions/WarpActionInputType"
        }
      },
      "required": ["name", "type", "position", "source"],
      "type": "object"
    },
    "WarpActionInputPosition": {
      "enum": [
        "receiver",
        "value",
        "transfer",
        "arg:1",
        "arg:2",
        "arg:3",
        "arg:4",
        "arg:5",
        "arg:6",
        "arg:7",
        "arg:8",
        "arg:9",
        "arg:10",
        "data"
      ],
      "type": "string"
    },
    "WarpActionInputSource": {
      "enum": ["field", "query"],
      "type": "string"
    },
    "WarpActionInputType": {
      "type": "string"
    },
    "WarpActionType": {
      "enum": ["transfer", "contract", "query", "collect", "link"],
      "type": "string"
    },
    "WarpCollectAction": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": ["string", "null"]
        },
        "destination": {
          "additionalProperties": false,
          "properties": {
            "headers": {
              "additionalProperties": {
                "type": "string"
              },
              "type": "object"
            },
            "method": {
              "enum": ["GET", "POST"],
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          },
          "required": ["url", "method", "headers"],
          "type": "object"
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "next": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        }
      },
      "required": ["type", "label", "destination"],
      "type": "object"
    },
    "WarpContractAction": {
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "string"
        },
        "args": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "description": {
          "type": ["string", "null"]
        },
        "func": {
          "type": ["string", "null"]
        },
        "gasLimit": {
          "type": "number"
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "next": {
          "type": "string"
        },
        "transfers": {
          "items": {
            "$ref": "#/definitions/WarpContractActionTransfer"
          },
          "type": "array"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        },
        "value": {
          "type": "string"
        }
      },
      "required": ["type", "label", "address", "func", "args", "gasLimit"],
      "type": "object"
    },
    "WarpContractActionTransfer": {
      "additionalProperties": false,
      "properties": {
        "amount": {
          "type": "string"
        },
        "nonce": {
          "type": "number"
        },
        "token": {
          "type": "string"
        }
      },
      "required": ["token"],
      "type": "object"
    },
    "WarpLinkAction": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": ["string", "null"]
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        },
        "url": {
          "type": "string"
        }
      },
      "required": ["type", "label", "url"],
      "type": "object"
    },
    "WarpMeta": {
      "additionalProperties": false,
      "properties": {
        "createdAt": {
          "type": "string"
        },
        "creator": {
          "type": "string"
        },
        "hash": {
          "type": "string"
        }
      },
      "required": ["hash", "creator", "createdAt"],
      "type": "object"
    },
    "WarpQueryAction": {
      "additionalProperties": false,
      "properties": {
        "abi": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "args": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "description": {
          "type": ["string", "null"]
        },
        "func": {
          "type": "string"
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        }
      },
      "required": ["type", "label", "address", "func", "args"],
      "type": "object"
    },
    "WarpTransferAction": {
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "string"
        },
        "data": {
          "type": "string"
        },
        "description": {
          "type": ["string", "null"]
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "type": "string"
        },
        "next": {
          "type": "string"
        },
        "transfers": {
          "items": {
            "$ref": "#/definitions/WarpContractActionTransfer"
          },
          "type": "array"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        },
        "value": {
          "type": "string"
        }
      },
      "required": ["type", "label"],
      "type": "object"
    },
    "WarpVarPlaceholder": {
      "type": "string"
    }
  }
}

=== vLeapGroup/warps-specs/examples/transfer.json
{
  "protocol": "warp:1.0.0",
  "name": "Transfer",
  "title": "Asset Transfer",
  "description": "Transfer an asset from one account to another.",
  "actions": [
    {
      "type": "transfer",
      "label": "Send now",
      "inputs": [
        {
          "name": "Receiver",
          "bot": "The blockchain address of the receiver.",
          "type": "address",
          "position": "receiver",
          "source": "field",
          "required": true
        },
        {
          "name": "Asset",
          "bot": "The asset to transfer. Construct the format as follows from the user input: 'USH-123456|0|5' (id|nonce|amount)",
          "type": "esdt",
          "position": "transfer",
          "source": "field",
          "required": true
        }
      ]
    }
  ]
}

=== vLeapGroup/warps-specs/examples/peerme/manager-boost.json
{
  "protocol": "warp:1.0.0",
  "name": "PeerMe: Boost",
  "title": "Boost xAlliance",
  "description": "Boost xAlliance with USDC to increase the DAOs energy.",
  "vars": {
    "AMOUNT": "query:amount"
  },
  "actions": [
    {
      "type": "contract",
      "label": "Boost now",
      "address": "erd1qqqqqqqqqqqqqpgqtatmxjhlxkehl37u5kz9tz7sm450xd7f27rsppynzj",
      "func": "boost",
      "args": [
        "address:erd1qqqqqqqqqqqqqpgqsrkgkrv594hnruqphmtera490a6tzvmz27rsggj6an"
      ],
      "gasLimit": 20000000,
      "inputs": [
        {
          "name": "USDC amount",
          "type": "esdt",
          "position": "transfer",
          "source": "field",
          "required": true,
          "options": ["USDC-c76f1f"]
        }
      ]
    }
  ]
}

=== vLeapGroup/warps-specs/examples/coffee-tip.json
{
  "protocol": "warp:1.3.0",
  "name": "Coffee Tip",
  "title": "Tip me a coffee",
  "description": "Tip me a coffee to support my work.",
  "preview": "https://i.ibb.co/KcfzWRGX/5-B55239-A-88-B2-46-D6-B940-03-FABAF20-E4-F.png",
  "actions": [
    {
      "type": "transfer",
      "label": "Tip now",
      "address": "erd1vgsjr29269khudx8ej5znvasa3g0axs0kz6k62yrwsgsl0cj8sdsxjflpe",
      "inputs": [
        {
          "name": "Amount",
          "type": "biguint",
          "position": "value",
          "source": "field",
          "required": true,
          "modifier": "scale:18"
        }
      ]
    }
  ]
}
