=== vLeapGroup/warps-specs/schemas/v3.0.0.schema.json
{
  "$ref": "#/definitions/Warp",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Warp": {
      "additionalProperties": false,
      "properties": {
        "actions": {
          "items": {
            "$ref": "#/definitions/WarpAction"
          },
          "type": "array"
        },
        "bot": {
          "type": "string"
        },
        "chain": {
          "$ref": "#/definitions/WarpChain"
        },
        "description": {
          "anyOf": [
            {
              "$ref": "#/definitions/WarpText"
            },
            {
              "type": "null"
            }
          ]
        },
        "messages": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "meta": {
          "$ref": "#/definitions/WarpMeta"
        },
        "name": {
          "type": "string"
        },
        "next": {
          "type": "string"
        },
        "preview": {
          "type": "string"
        },
        "protocol": {
          "type": "string"
        },
        "results": {
          "additionalProperties": {
            "$ref": "#/definitions/WarpResulutionPath"
          },
          "type": "object"
        },
        "title": {
          "$ref": "#/definitions/WarpText"
        },
        "vars": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      },
      "required": ["protocol", "name", "title", "description", "actions"],
      "type": "object"
    },
    "WarpAction": {
      "anyOf": [
        {
          "$ref": "#/definitions/WarpTransferAction"
        },
        {
          "$ref": "#/definitions/WarpContractAction"
        },
        {
          "$ref": "#/definitions/WarpQueryAction"
        },
        {
          "$ref": "#/definitions/WarpCollectAction"
        },
        {
          "$ref": "#/definitions/WarpLinkAction"
        }
      ]
    },
    "WarpActionInput": {
      "additionalProperties": false,
      "properties": {
        "as": {
          "type": "string"
        },
        "bot": {
          "type": "string"
        },
        "default": {
          "type": ["string", "number", "boolean"]
        },
        "description": {
          "anyOf": [
            {
              "$ref": "#/definitions/WarpText"
            },
            {
              "type": "null"
            }
          ]
        },
        "label": {
          "$ref": "#/definitions/WarpText"
        },
        "max": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "$ref": "#/definitions/WarpVarPlaceholder"
            }
          ]
        },
        "min": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "$ref": "#/definitions/WarpVarPlaceholder"
            }
          ]
        },
        "modifier": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "options": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            {
              "additionalProperties": {
                "type": "string"
              },
              "type": "object"
            }
          ]
        },
        "pattern": {
          "type": "string"
        },
        "patternDescription": {
          "$ref": "#/definitions/WarpText"
        },
        "position": {
          "$ref": "#/definitions/WarpActionInputPosition"
        },
        "required": {
          "type": "boolean"
        },
        "source": {
          "$ref": "#/definitions/WarpActionInputSource"
        },
        "type": {
          "$ref": "#/definitions/WarpActionInputType"
        }
      },
      "required": ["name", "type", "source"],
      "type": "object"
    },
    "WarpActionInputPosition": {
      "type": "string"
    },
    "WarpActionInputSource": {
      "enum": ["field", "query", "user:wallet", "hidden"],
      "type": "string"
    },
    "WarpActionInputType": {
      "type": "string"
    },
    "WarpActionType": {
      "enum": ["transfer", "contract", "query", "collect", "link"],
      "type": "string"
    },
    "WarpChain": {
      "type": "string"
    },
    "WarpCollectAction": {
      "additionalProperties": false,
      "properties": {
        "auto": {
          "type": "boolean"
        },
        "description": {
          "anyOf": [
            {
              "$ref": "#/definitions/WarpText"
            },
            {
              "type": "null"
            }
          ]
        },
        "destination": {
          "additionalProperties": false,
          "properties": {
            "headers": {
              "additionalProperties": {
                "type": "string"
              },
              "type": "object"
            },
            "method": {
              "enum": ["GET", "POST", "PUT", "DELETE"],
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          },
          "required": ["url"],
          "type": "object"
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "$ref": "#/definitions/WarpText"
        },
        "next": {
          "type": "string"
        },
        "primary": {
          "type": "boolean"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        }
      },
      "required": ["type", "label", "destination"],
      "type": "object"
    },
    "WarpContractAction": {
      "additionalProperties": false,
      "properties": {
        "abi": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "args": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "auto": {
          "type": "boolean"
        },
        "description": {
          "anyOf": [
            {
              "$ref": "#/definitions/WarpText"
            },
            {
              "type": "null"
            }
          ]
        },
        "func": {
          "type": ["string", "null"]
        },
        "gasLimit": {
          "type": "number"
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "$ref": "#/definitions/WarpText"
        },
        "next": {
          "type": "string"
        },
        "primary": {
          "type": "boolean"
        },
        "transfers": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        },
        "value": {
          "type": "string"
        }
      },
      "required": ["type", "label", "gasLimit"],
      "type": "object"
    },
    "WarpI18nText": {
      "additionalProperties": {
        "type": "string"
      },
      "type": "object"
    },
    "WarpLinkAction": {
      "additionalProperties": false,
      "properties": {
        "auto": {
          "type": "boolean"
        },
        "description": {
          "anyOf": [
            {
              "$ref": "#/definitions/WarpText"
            },
            {
              "type": "null"
            }
          ]
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "$ref": "#/definitions/WarpText"
        },
        "primary": {
          "type": "boolean"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        },
        "url": {
          "type": "string"
        }
      },
      "required": ["type", "label", "url"],
      "type": "object"
    },
    "WarpMeta": {
      "additionalProperties": false,
      "properties": {
        "chain": {
          "$ref": "#/definitions/WarpChain"
        },
        "createdAt": {
          "type": "string"
        },
        "creator": {
          "type": "string"
        },
        "hash": {
          "type": "string"
        }
      },
      "required": ["chain", "hash", "creator", "createdAt"],
      "type": "object"
    },
    "WarpQueryAction": {
      "additionalProperties": false,
      "properties": {
        "abi": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "args": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "auto": {
          "type": "boolean"
        },
        "description": {
          "anyOf": [
            {
              "$ref": "#/definitions/WarpText"
            },
            {
              "type": "null"
            }
          ]
        },
        "func": {
          "type": "string"
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "$ref": "#/definitions/WarpText"
        },
        "next": {
          "type": "string"
        },
        "primary": {
          "type": "boolean"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        }
      },
      "required": ["type", "label"],
      "type": "object"
    },
    "WarpResulutionPath": {
      "type": "string"
    },
    "WarpText": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "$ref": "#/definitions/WarpI18nText"
        }
      ]
    },
    "WarpTransferAction": {
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "string"
        },
        "auto": {
          "type": "boolean"
        },
        "data": {
          "type": "string"
        },
        "description": {
          "anyOf": [
            {
              "$ref": "#/definitions/WarpText"
            },
            {
              "type": "null"
            }
          ]
        },
        "inputs": {
          "items": {
            "$ref": "#/definitions/WarpActionInput"
          },
          "type": "array"
        },
        "label": {
          "$ref": "#/definitions/WarpText"
        },
        "next": {
          "type": "string"
        },
        "primary": {
          "type": "boolean"
        },
        "transfers": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "type": {
          "$ref": "#/definitions/WarpActionType"
        },
        "value": {
          "type": "string"
        }
      },
      "required": ["type", "label"],
      "type": "object"
    },
    "WarpVarPlaceholder": {
      "type": "string"
    }
  }
}

=== vLeapGroup/warps-specs/examples/multiversx/staking-rewards-claim-all.json
{
  "protocol": "warp:2.0.0",
  "name": "MultiversX Staking: Claim All",
  "title": "Claim All Staking Rewards",
  "description": "Claim all staking rewards for the current user.",
  "vars": {
    "USER_WALLET": "user:wallet"
  },
  "actions": [
    {
      "type": "collect",
      "label": "Check rewards",
      "destination": {
        "url": "https://devnet-api.multiversx.com/accounts/{{USER_WALLET}}/delegation"
      }
    }
  ],
  "results": {
    "DELEGATIONS": "out"
  },
  "next": "staking-rewards-claim?contract={{DELEGATIONS[].contract}}"
}

=== vLeapGroup/warps-specs/examples/vleap/raffle-create.json
{
  "protocol": "warp:1.3.0",
  "name": "Raffle: Create",
  "title": "Create a new Raffle",
  "description": "<p>Create a simple raffle and receive its unique ID. This ID can then be used to create a Participation Warp.</p>",
  "preview": "https://vleap.io/images/external/warps/raffle-create.jpg",
  "actions": [
    {
      "type": "contract",
      "label": "Create now",
      "address": "erd1qqqqqqqqqqqqqpgqht0nht73ewg4mxr8nd89v5p8cfryjjlfl3tskqtqpw",
      "func": "createRaffle",
      "args": ["biguint:1000000000000000"],
      "gasLimit": 10000000,
      "abi": "hash:1994371711aa2541fa0b36f79659bc97decc4baadcb69162aeadaf002716c383",
      "inputs": []
    }
  ],
  "results": {
    "RAFFLE_ID": "out.1"
  },
  "messages": {
    "success": "Raffle with ID {{RAFFLE_ID}} created successfully!",
    "error": "Failed to create raffle. Please try again."
  },
  "next": "participate-raffle?raffle={{RAFFLE_ID}}"
}

=== vLeapGroup/warps-specs/examples/xexchange/swap-cols.json
{
  "protocol": "warp:2.0.0",
  "name": "xExchange: Swap eGold to COLS",
  "title": "Swap eGold to COLS",
  "description": "Swap eGold to COLS on xExchange.",
  "actions": [
    {
      "type": "contract",
      "label": "Swap now",
      "address": "erd1qqqqqqqqqqqqqpgq3r2vzqe89x23lryqmlp9xynf9t46qnpa2jpsrh63az",
      "func": "swapTokensFixedInput",
      "args": ["string:COLS-9d91b7", "biguint:1"],
      "gasLimit": 10000000,
      "inputs": [
        {
          "name": "WEGLD Amount",
          "type": "esdt",
          "position": "transfer",
          "source": "field",
          "required": true,
          "min": 1,
          "options": ["WEGLD-a28c59"]
        }
      ]
    }
  ],
  "results": {
    "OUTPUT_TOKENS": "out.multiPairSwap.5"
  },
  "messages": {
    "success": "Swapped successful and received {{OUTPUT_TOKENS}}"
  },
  "next": "peerme-earn-distribute?"
}

=== vLeapGroup/warps-specs/examples/multiversx/staking-rewards-claim.json
{
  "protocol": "warp:2.0.0",
  "name": "MultiversX Staking: Claim Rewards",
  "title": "Claim Staking Rewards",
  "description": "Claim staking rewards for the current user.",
  "vars": {
    "CONTRACT_ADDRESS": "query:contract"
  },
  "actions": [
    {
      "type": "contract",
      "label": "Claim now",
      "address": "{{CONTRACT_ADDRESS}}",
      "func": "claimRewards",
      "args": [],
      "gasLimit": 10000000
    }
  ],
  "messages": {
    "success": "Rewards claimed successfully"
  }
}

=== vLeapGroup/warps-specs/examples/multiversx/staking-delegate.json
{
  "protocol": "warp:2.0.0",
  "name": "MultiversX Staking: Stake",
  "title": "Stake eGold",
  "description": "Stake eGold to secure the network and earn rewards.",
  "vars": {
    "CONTRACT_ADDRESS": "query:contract"
  },
  "actions": [
    {
      "type": "contract",
      "label": "Stake now",
      "address": "{{CONTRACT_ADDRESS}}",
      "func": "delegate",
      "args": [],
      "gasLimit": 10000000,
      "inputs": [
        {
          "name": "value",
          "description": "Amount of eGold to delegate.",
          "type": "biguint",
          "position": "value",
          "source": "field",
          "required": true,
          "min": 1,
          "modifier": "scale:18"
        }
      ]
    },
    {
      "type": "link",
      "label": "Learn more",
      "description": "Find more information about staking eGold.",
      "url": "https://multiversx.com/egld"
    }
  ],
  "messages": {
    "success": "eGold staked successfully"
  }
}

=== vLeapGroup/warps-specs/examples/multiversx/staking-rewards-redelegate-all.json
{
  "protocol": "warp:2.0.0",
  "name": "MultiversX: Delegations",
  "title": "Retrieve Delegations",
  "description": "Retrieve the delegations of a user.",
  "vars": {
    "USER_WALLET": "user:wallet"
  },
  "actions": [
    {
      "type": "collect",
      "label": "Retrieve Delegations",
      "destination": {
        "url": "https://devnet-api.multiversx.com/accounts/{{USER_WALLET}}/delegation"
      }
    }
  ],
  "results": {
    "DELEGATIONS": "out"
  },
  "next": "staking-rewards-redelegate?contract={{DELEGATIONS[].contract}}"
}

=== vLeapGroup/warps-specs/examples/multiversx/narrative.json
{
  "protocol": "warp:1.3.0",
  "name": "MultiversX: Narrative",
  "title": "The MultiversX Narrative ",
  "preview": "https://vleap.ai/images/external/warps/momentum-podcast.png",
  "description": "What do you think is the most interesting and attractive narrative for MultiversX?",
  "actions": [
    {
      "type": "transfer",
      "label": "Submit now",
      "address": "erd1qs63mw9997vkdahyqhtfmh0e36gcgyyppwrl8xdrh4ykjyfvfl3qhe56cx",
      "inputs": [
        {
          "name": "Narrative",
          "type": "string",
          "position": "data",
          "source": "field",
          "required": true
        }
      ]
    }
  ],
  "messages": {
    "success": "Your narrative has been submitted!"
  }
}

=== vLeapGroup/warps-specs/examples/xexchange/xexchange-swap-super.json
{
  "protocol": "warp:0.1.0",
  "name": "xExchange: Swap eGold to SUPER",
  "title": "Swap eGold to SUPER",
  "description": "Swap eGold to SUPER on xExchange.",
  "preview": "https://vleap.ai/images/external/warps/xexchange-swap.png",
  "actions": [
    {
      "type": "contract",
      "label": "Swap now",
      "address": "erd1qqqqqqqqqqqqqpgq957r57dca0h6avq2mtfd7tvxlhcp3r4y0n4sdq7clt",
      "func": "swapTokensFixedInput",
      "args": ["string:SUPER-19c5c5", "biguint:1"],
      "gasLimit": 10000000,
      "inputs": [
        {
          "name": "WEGLD Amount",
          "type": "esdt",
          "position": "transfer",
          "source": "field",
          "required": true,
          "min": 1,
          "options": ["WEGLD-a28c59"]
        }
      ]
    }
  ],
  "results": {
    "OUTPUT_TOKENS": "out.multiPairSwap.5"
  },
  "messages": {
    "success": "Swapped successful and received {{OUTPUT_TOKENS}}"
  }
}
